let password='',poster='',entries=[];const form=document.getElementById('announcement'),message=document.getElementById('message');
function say(text){message.textContent=text;}
async function request(method,data){const r=await fetch('/api/updates?admin=1',{method,headers:{Authorization:'Bearer '+password,'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const result=await r.json();if(!r.ok)throw Error(result.error||'Unable to save');return result;}
function preview(){const img=document.getElementById('poster-preview');img.hidden=!poster;img.src=poster;}
function edit(x){form.reset();for(const field of ['id','title','type','date','location','summary','body','status'])form.elements[field].value=x[field]||'';poster=x.poster||'';preview();}
function fresh(){edit({id:crypto.randomUUID(),type:'news',status:'draft',date:new Date().toISOString().slice(0,10)});}
async function load(){entries=await request('GET');const list=document.getElementById('entries');list.replaceChildren();entries.sort((a,b)=>b.date.localeCompare(a.date)).forEach(x=>{const b=document.createElement('button');b.type='button';b.className='admin-entry';b.textContent=x.title+' ('+x.status+')';b.addEventListener('click',()=>{edit(x);say('Editing: '+x.title);});list.append(b);});}
document.getElementById('login').addEventListener('submit',async e=>{e.preventDefault();password=document.getElementById('password').value;say('Signing in…');try{await load();document.getElementById('login').hidden=true;document.getElementById('editor').hidden=false;document.getElementById('password').value='';fresh();say('Signed in. Select an announcement or create a new one.');}catch(e){password='';say(e.message);}});
document.getElementById('logout').onclick=()=>{password='';entries=[];form.reset();poster='';document.getElementById('editor').hidden=true;document.getElementById('login').hidden=false;say('Signed out.');};
document.getElementById('new').onclick=()=>{if(confirm('Start a new announcement? Any unsaved edits will be discarded.')){fresh();say('New announcement');}};
document.getElementById('remove-poster').onclick=()=>{poster='';document.getElementById('poster').value='';preview();};
document.getElementById('poster').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>250*1024){say('Choose a PNG, JPEG or WebP poster no larger than 250 KB.');e.target.value='';return;}const reader=new FileReader();reader.onload=()=>{poster=reader.result;preview();};reader.readAsDataURL(file);};
form.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.poster=poster;const button=document.getElementById('save');button.disabled=true;say('Saving…');try{await request('POST',data);await load();say(data.status==='published'?'Published. The announcement is visible on the website.':'Saved as '+data.status+'.');}catch(e){say(e.message);}finally{button.disabled=false;}});
